### PR TITLE
Ui

### PR DESCRIPTION
**Pull request by drognanar**
Updates the UI.

Uses Ionicons for button icons.
Adds a resizable splitter for the see also panel (issue #410).
Adds a new tab button.
Adds tooltips to buttons.
Fix quirks with the toc delegate under windows (issue #262).
Makes UI rendering more consistent by separating state changes and UI changes.

### CODE REVIEW

**Comment by trollixx** [comment]
These all are great improvements. Unfortunately, I really don't know how to approach this PR. Stupid GitHub, it would be so great to have each commit as a separate pull-request. Should I start commenting the code, it might be quite annoying to search what commit a specific comment is related to.

There are several ways we can proceed:
* You split this PR on per commit basis and we deal with them one by one.
* We handle all of them at once here, if you are OK with a good amount of interactive rebasing.
* I could amend everything as needed and merge independently. Of course, all commits would keep you as an author.

You choose :)

**Comment by drognanar** [comment]
I managed to split the PR into three separate PRs as the commits were rather independent.
For the remaining work required (includng the perf PR) I'd rather do any changes necessary as a series of extra commits/rebases.

**Comment by mrhota** [comment]
Is there a way anyone else could we give a hand so this can be moved along?

**Comment by mrhota** [comment]
@trollixx what's the status? anything I can do to help? Some great performance improvements are waiting on this.

**Comment by trollixx** [comment]
Changes, that were split from this PR, have been already merged. What's left is all mixed in one commit, and cannot be merged as-is. Regarding the second PR with performance fixes, I am looking into it, and hopefully get it merged soon.

**Comment by drognanar** [comment]
Another update
The PR is now smaller in size and contains the first part of UI changes

**Comment by trollixx** [comment]
After looking more into this, I doesn't look like the right approach.

On Linux Zeal relies on FreeDesktop icon theme, otherwise it wouldn't look consistent with other apps.

As for Windows, we should bundle some icons, and then set icon theme [path](http://doc.qt.io/qt-5/qicon.html#setThemeSearchPaths) and [name](http://doc.qt.io/qt-5/qicon.html#setThemeName), so those icons would be picked up automatically. Perhaps, there's a way to retrieve system icons used by other Windows applications, but I am unaware how.

I am closing this PR, but still thank you for contributing!

Commit b87890c275430fdcf5d17199dfbf9ef9836492da (`ui: Convert go to url button into a ToolButton `) has been incorporated as one of the recent UI refactoring changes.

**Pull request closed without merging**
