### PR TITLE
fix: Some macos user unstandard library path cause LibArchive_INCLUDE…

### PR DESCRIPTION
**Pull request by yunfengsay**
https://github.com/zealdocs/zeal/issues/1364

### CODE REVIEW

**Comment by trollixx** [comment]
Any idea why CMake cannot discover this path on its own?

**Comment by stefangehn** [comment]
Just like PR #1386 I think this is a matter of telling cmake and its standard LibArchive lookup where to find a non-standard libarchive installation.

**Comment by trollixx** [comment]
Okay, looks like this is an issue due to Homebrew's installation path. 

* https://github.com/Homebrew/legacy-homebrew/issues/21415

**Comment by trollixx** [comment]
whoops. I messed the PR up trying to rebase, will push manually.

**Comment by trollixx** [comment]
Pushed as 294800645e5f50fb7ef2f1e4dbb69658b0d64a60. Thanks!

**Pull request closed without merging**
