### PR TITLE
Implement dash:// and dash-plugin:// URL scheme

### LINKED ISSUE #247: dash:// url scheme support on Windows
Mostly due to the lack of an installer on Windows there is no easy way to open Zeal right now. Because of this the Intellij plugin cannot properly support Zeal on Windows right now (relevant discussion: https://github.com/gdelmas/IntelliJDashPlugin/issues/36#issuecomment-69078880)

Here's an example of a Windows register file to support Zeal:
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\dash]
@="Zeal Search (Dash Protocol)"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\dash\DefaultIcon]
@="C:\\Program Files (x86)\\Zeal\\Zeal.exe,1"

[HKEY_CLASSES_ROOT\dash\shell]

[HKEY_CLASSES_ROOT\dash\shell\open]

[HKEY_CLASSES_ROOT\dash\shell\open\command]
@="\"C:\\Program Files (x86)\\Zeal\\Zeal.exe\" --query \"%1\""

[HKEY_CLASSES_ROOT\dash-plugin]
@="Zeal Search (Dash Plugin Protocol)"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\dash-plugin\DefaultIcon]
@="C:\\Program Files (x86)\\Zeal\\Zeal.exe,1"

[HKEY_CLASSES_ROOT\dash-plugin\shell]

[HKEY_CLASSES_ROOT\dash-plugin\shell\open]

[HKEY_CLASSES_ROOT\dash-plugin\shell\open\command]
@="\"C:\\Program Files (x86)\\Zeal\\Zeal.exe\" --query \"%1\""
```

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/7569457-dash-url-scheme-support-on-windows?utm_campaign=plugin&utm_content=tracker%2F295069&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F295069&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by lowjoel**
Fixes #247.

Comments welcome.

### CODE REVIEW

**Comment by trollixx** [comment]
Hi, thank you for the contribution!

I see some issues, that need to be resolved before merging.

1. First of all, the current implementation simple won't compile under Linux (`registerProtocol` is not defined).

2. Another problem is the conflict with 73e7d918fe90ac79aae923a223de205d26d8c90f. There could be no data sent over the local socket, but just a connection would signal to bring Zeal window up.

3. Also, what about a situation, when there's no Zeal instance running? As far as I can see, such case is not handled at all.

There are also coding style issues. I am trying hard to polish the code and make it look better. I am trying to follow [Qt](http://qt-project.org/wiki/Qt_Coding_Style) and [Qt Creator](http://doc.qt.digia.com/qtcreator-extending/coding-style.html) coding style guidelines.

Also, I think it would make sense to squash all three commits in one.

Are you comfortable with working on your pull request?

**Comment by lowjoel** [comment]
Hi @trollixx, I've fixed point 1. I've made all other platforms have a no-op (since I'm not sure what the platform behaviours should be.). I've also handled point 3, when there is no Zeal instance running.

For coding styles, could you point out specific places where I should change? I've read the documents but probably you'll be quicker in pointing out violations.

I'll squash them when you're done reviewing everything.

**Comment by lowjoel** [comment]
For point 2, if there is no query specified, it will still send a blank query over the socket, in main.cpp:95.

**Comment by trollixx** [comment]
Sounds good. I'll make a detailed review later today. In meanwhile you if could rebase changes on top of master, that should make CI work.

**Comment by lowjoel** [comment]
@trollixx There were some extra changes I needed to make for Zeal to compile on MSVC on Windows. Do you want them as a separate PR?

**Comment by lowjoel** [comment]
@trollixx I already did rebase on top of master, Shippable builds still failing

(any way to see the build output, like Travis?)

**Comment by trollixx** [comment]
Just click on the red cross near the commit id or in the [pull request list](https://github.com/zealdocs/zeal/pulls) to see the CI build log. Currently this PR is based on top of 73e7d918fe90ac79aae923a223de205d26d8c90f, that had CI issues. Please rebase on top of 09840e89ac892d33dfcd79190fbe4fd270f79b17. Sorry, for all this hassle with CI.

A MSVC compatibility PR would be very appreciated, unless it meant to workaround missing C++11 features. I am really not aware how good C++11 support MSVC provides nowadays.

**Comment by lowjoel** [comment]
I tried that, and I just got sent to the home page of Shippable.

The fixes for MSVC involves the QStringLiteral class because of the use of wide characters on Windows.

**Comment by trollixx** [comment]
I guess that's Shippable issues. Looks like it's not possible to view the build history unless you are the owner of the project. At least I cannot find any settings. Only the [last build](https://app.shippable.com/projects/54ac2ce4d46935d5fbc19b84/builds/latest) is visible to everyone. I am going to add Travis-CI builds soon.

Anyway, all previous failures have nothing to do with the PR, but rather are my mistakes in the build configuration :(

Regarding MSVC fixes, sure, PR would be welcomed.

**Comment by lowjoel** [comment]
@trollixx it passes!

**Comment by lowjoel** [comment]
Any comments before I squash this down?

**Comment by trollixx** [comment]
Hi, obviously, the PR goes in. I just want to test it on my own, and for that I need a Windows environment. I'll check it out in the nearest days. Sorry for the delay.

**Comment by trollixx** [comment]
I've added protocol support for Windows in 8cb473a54e7ab0d44a7eece19c94bfdba3c974f1. It's done in a slightly different way, to minimise amount of code, allow easier integration with installers, and to work on any platform.

Regardless,  big thanks for the PR! It helped me to figure out a universal way of handling different queries.

**Comment by lowjoel** [comment]
Good to know! I'm happy regardless, because I get to integrate my IDE =)

**Pull request closed without merging**
