### PR TITLE
Port to Qt6

### PR DESCRIPTION
**Pull request by Arthapz**

### CODE REVIEW

**Comment by mohamad-supangat** [comment]
@barthalion hay do you have any change about this qt6 port

**Comment by mohamad-supangat** [comment]
@barthalion hay do you have any change about this qt6 port? ??

**Comment by trollixx** [comment]
Thanks for the PR but I believe it's vital to keep support for Qt 5. Also significant amount of changes here are whitespace only, which would not be accepted. I have a dated local branch which builds with both Qt 5 and Qt 6. I'll push it shortly.

**Comment by trollixx** [comment]
I've just pushed draft as #1420.

**Pull request closed without merging**
