### PR TITLE
Resize icons to standard dimensions

### PR DESCRIPTION
**Pull request by SammaySarkar**
Windows icon & icon resources had dimensions like 17x17, 32x33, 128x129 etc. Square-ized them.

### CODE REVIEW

**Comment by trollixx** [comment]
Great, thanks! Could you please change commit message to `Resize icons to standard dimensions`? 

Then I'll manually merge it to 0.1 branch to make it part of the next maintenance release.

**Comment by trollixx** [comment]
Oh, now there are two commits. Please, squash them and do a force push to the same branch.

**Comment by SammaySarkar** [comment]
Sorry. OK now?

**Comment by trollixx** [comment]
Perfect, thank you!.

**Comment by SammaySarkar** [comment]
:smiley:  my pleasure!

**Comment by trollixx** [comment]
Manually cherry-picked into 0.1 branch: ab317d048520de21b2c96ab5ea6b0a25ed504679.

**Pull request closed without merging**
