### PR TITLE
Fix issue 436

### PR DESCRIPTION
**Pull request by Serge45**
Fix issue #436 by
 - Implement removeRows function for SearchModel
 - Remove all items in SearchModel for active tab after removing corresponding docset.

### CODE REVIEW

**Comment by drognanar** [comment]
When the removed docset is a part of search results zeal still crashes.

**Comment by jkozera** [comment]
It still crashed for me, I suspect because of missing `beginRemoveRows` and `endRemoveRows` calls. I've created a new PR (#457) to address this. (It now seems to work right, no crashes, with the addition of a131234beaa61e3bc1c30b74567378fc7b998d6c.)

**Comment by trollixx** [comment]
Thank you for looking in the issue.

`searchState->sectionsList` can be just reset with `setResults();` instead of removing items row by row.

I don't really like the idea of iterating over the whole `searchState->zealSearch` to remove docset-specific items, it might take a while when iterating over decent number of heavy docsets. But it's still better than crashing.

First of all, please rebase the change on top of `master` branch, and squash all commits. It would also make sense to incorporate changes from @jkozera's pull request, as I don't want to merge a broken commit. I hope Jerzy would not object :)

Also, commit message should be something like `registry, ui: Fix crash on docset removal (fixes #436)`.

**Comment by Serge45** [comment]
Hi, I've updated this PR based on @jkozera 's PR(#457) and squashed all commits, but after rebase, @jkozera 's commit message disappears. Is there any way to keep it?

**Comment by jkozera** [comment]
Don't worry, I don't mind losing that commit message with the rebase, so feel free to merge it as is. :)

**Pull request merged**
