### PR TITLE
Adds an input bar for filtering available docsets

### PR DESCRIPTION
**Pull request by brunoro**
Makes browsing through the list of downloadable docsets easier.
filter_docsets
filter_docsets_php

### CODE REVIEW

**Comment by jkozera** [comment]
:+1: Thanks! Looks good to me, let's hope @trollixx gets some spare time for reviewing it too. :)

**Comment by joaomsa** [comment]
:+1: works great for me too

**Comment by trollixx** [comment]
It's a nice feature. The problem here is the unhiding of already installed docsets. Here's a an improved version of `SettingsDialog::updateDocsetFilter()` method, that fixes the problem and eliminates extra loop over the whole list (in `QListWidget::findItems()`):

```c++
void SettingsDialog::updateDocsetFilter(const QString &filterString)
{
    const bool doSearch = !filterString.simplified().isEmpty();

    for (int i = 0; i < ui->availableDocsetList->count(); ++i) {
        QListWidgetItem *item = ui->availableDocsetList->item(i);

        // Skip installed docsets
        if (m_docsetRegistry->contains(item->data(ListModel::DocsetNameRole).toString()))
            continue;

        item->setHidden(doSearch && !item->text().contains(filterString, Qt::CaseInsensitive));
    }
}
```

Please also update the commit message to something like `ui: Implement filtering of available docsets in Settings`. 

I'll merge as soon as soon as it's ready. Thanks!

**Comment by brunoro** [comment]
Why would you like to skip the installed docsets? I'd see it as a valid use case to use the filter bar to find a docset I want to uninstall.

Also, is there any advantage of doing multiple `contains` calls on QString instead of using the `findItems` method of QList, or is it just a matter of style?

**Comment by trollixx** [comment]
> Why would you like to skip the installed docsets? I'd see it as a valid use case to use the filter bar to find a docset I want to uninstall.

The installed docsets are already visible in the list above. The `Available Docsets` list is only for docsets that can be installed.

> Also, is there any advantage of doing multiple `contains` calls on QString instead of using the `findItems` method of QList, or is it just a matter of style?

If you check the source if [`QListWidget::findItems()`](http://code.woboq.org/qt5/qtbase/src/widgets/itemviews/qlistwidget.cpp.html#_ZNK11QListWidget9findItemsERK7QString6QFlagsIN2Qt9MatchFlagEE), you'll see that [`QAbstractItemModel::match()`](http://code.woboq.org/qt5/qtbase/src/corelib/itemmodels/qabstractitemmodel.cpp.html#_ZNK18QAbstractItemModel5matchERK11QModelIndexiRK8QVarianti6QFlagsIN2Qt9MatchFlagEE) it calls does even more complicated stuff inside. And [then](http://code.woboq.org/qt5/qtbase/src/widgets/itemviews/qlistwidget.cpp.html#1728) there's an additional loop over results returned by `QAbstractItemModel::match()`.

**Comment by brunoro** [comment]
I see. I'll make the changes later and update the PR.

**Comment by drognanar** [comment]
Call to `QListWidget::findItems` is already used in `SettingsDialog::findDocsetListItem`. Personally, to keep consistency I would make both methods manually iterate over items or call `
QListWidget::findItems()`.

**Comment by drognanar** [comment]
Also it seems that more and more places are responsible for managing the visibility state of available docsets. As usual this causes bugs. One example is if the docset directory is changed. A docset is then removed from the installed docsets list but still hidden in available docsets list.

To resolve the issue `updateDocsetFilter` should also be called once the available list gets initially populated and also whenever registry emits an add/remove event.

**Comment by trollixx** [comment]
@drognanar that's a valid point, see 32af98c00e6b3bd73671afc02e9c4540a0d6ec88.

**Comment by trollixx** [comment]
Regarding the second observation, please create a ticket, I'll fix that once this change is merged.

In fact I believe the most of the SettingsDialog code should go away (with #354) or be rewritten. For instance, download/unpack progress indication is also broken, and many other things.

**Comment by brunoro** [comment]
rebased + updated `SettingsDialog::updateDocsetFilter`

**Comment by trollixx** [comment]
Merged, thanks!

**Comment by brunoro** [comment]
(:

**Pull request merged**
