### PR TITLE
Implement restoring last session

### PR DESCRIPTION
**Pull request by innermous**
I need one thing from #538 to be rebased to make tab titles work properly. 
UPD. Forgot about commit messages style, will fix that with next patch set.

### CODE REVIEW

**Comment by innermous** [comment]
By the way. What if we save session every time application is closed?
This can give user two options 
* auto restore it on startup if user checked "Restore last session" in settings
* restore it explicitly when user explicitly wants it with Ctrl+Shift+T like browsers do

**Comment by trollixx** [comment]
This one is tricky. I've been thinking about allowing people to have several sessions similarly to Qt Creator's sessions or or even Firefox's profiles (see #546 too). I guess we can start with this, and then add more features.

What's actually bothering me, is adding more stuff to `MainWindow`. I've been working on moving things out, so all UI code could be eventually encapsulated in a plugin. How about coming up with an independent class (e.g. `SessionManager`), and letting it do all dirty work?

**Comment by trollixx** [comment]
Adding a reference to #78, which is the issue this patch attempts to resolve.

**Comment by innermous** [comment]
@trollixx I've never seen that issue, just noticed a tiny ToDo in the code. Thanks.

**Comment by trollixx** [comment]
Outdated, and requires a rewrite.

**Pull request closed without merging**
